import PROJECT1 from './Assets/Projects/Project-1.jpg';
import PROJECT2 from './Assets/Projects/Project-2.jpg';

export const PROJECTS = [
  {
    image: PROJECT1,
    name: 'Safelyshare',
    technologyUsed: 'ReactJs, Javascript, Firebase, Rest Api',
    description:
      'Safelyshare is a Online sharing platform which is created to reduce the waste generated by disposing the unwanted products. It lets user to lend their products to get passive income.',
    url: 'https://safelyshare.se/',
  },
  {
    image: PROJECT2,
    name: 'Cyber Shield',
    technologyUsed: 'Django, AWS, Python, MySQL ',
    description:
      'Cyber Shield is a state initiative focused on enhancing data security by safeguarding user information from unauthorized access and breaches. Which including encryption techniques using AWS Key Management Service (KMS)',
    url: 'https://github.com/arav-2003/Cyber-Shield',
  },
];

export const SKILLS = [
  { name: 'ReactJs', initialRating: 4 },
  { name: 'React-Native', initialRating: 4 },
  { name: 'JavaScript', initialRating: 4 },
  { name: 'Shopify/Reactjs', initialRating: 4 },
  { name: 'Nodejs', initialRating: 3 },
  { name: 'Html', initialRating: 4 },
  { name: 'CSS', initialRating: 4 },
  { name: 'TypeScript', initialRating: 4 },
  { name: 'MySQL', initialRating: 4 },
  { name: 'Git', initialRating: 5 },
  { name: 'Django', initialRating: 4 },
  { name: 'Python', initialRating: 4 },
  { name: 'Azure', initialRating: 3 },
  { name: 'Business Analyst', initialRating: 3 },
];

export const TOOLS = [
  'Visual Studio Code',
  'Git',
  'Chrome DevTools',
  'Npm (Node Package Manager)',
  'Firebase',
  'MySQL',
  'Power BI',
];
